package east.orientation.microlesson.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import east.orientation.microlesson.local.dao.Project;

import east.orientation.microlesson.greendao.ProjectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig projectDaoConfig;

    private final ProjectDao projectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        projectDaoConfig = daoConfigMap.get(ProjectDao.class).clone();
        projectDaoConfig.initIdentityScope(type);

        projectDao = new ProjectDao(projectDaoConfig, this);

        registerDao(Project.class, projectDao);
    }
    
    public void clear() {
        projectDaoConfig.clearIdentityScope();
    }

    public ProjectDao getProjectDao() {
        return projectDao;
    }

}
